import { NextResponse } from "next/server"
import { auth } from "@/lib/auth"
import prisma from "@/lib/prisma"
import { AIResponseError } from "@/lib/ai"
import { z } from "zod"
import { rateLimited, RATE_LIMITS } from "@/lib/rate-limit"
import { generateAndCacheTestQuestion, isTestQuestionInFlight } from "@/lib/test-question-prefetch"

// How long to wait for a question already being generated by the background
// prefetch before giving up and generating it ourselves
const IN_FLIGHT_WAIT_MS = 20_000
const IN_FLIGHT_POLL_MS = 500

const generateQuestionSchema = z.object({
  cardId: z.string(),
  direction: z.enum(["HANZI_TO_MEANING", "MEANING_TO_HANZI", "PINYIN_TO_HANZI"])
})

// POST /api/test-questions - Get or generate test question
export async function POST(req: Request) {
  try {
    const session = await auth()
    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const body = await req.json()
    const { cardId, direction } = generateQuestionSchema.parse(body)

    // Verify card belongs to user
    const card = await prisma.card.findUnique({
      where: { id: cardId },
      include: {
        deck: { select: { userId: true } },
        testQuestions: {
          where: { direction }
        }
      }
    })

    if (!card) {
      return NextResponse.json({ error: "Card not found" }, { status: 404 })
    }

    if (card.deck.userId !== session.user.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    // Check if question already cached
    let testQuestion = card.testQuestions[0]

    if (testQuestion) {
      // Update usage count (async, don't await to reduce latency)
      prisma.testQuestion.update({
        where: { id: testQuestion.id },
        data: { timesUsed: { increment: 1 } }
      }).catch(err => console.error("Failed to update usage count:", err))

      return NextResponse.json({
        cached: true,
        question: testQuestion
      })
    }

    // Generate new question via AI (cache hits above are not rate limited)
    const limited = rateLimited(`ai:light:${session.user.id}`, RATE_LIMITS.AI_LIGHT)
    if (limited) return limited

    // If the session-start prefetch is already generating this one, wait for it
    // to land rather than generating a duplicate
    const waitUntil = Date.now() + IN_FLIGHT_WAIT_MS
    while (isTestQuestionInFlight(cardId, direction) && Date.now() < waitUntil) {
      await new Promise((resolve) => setTimeout(resolve, IN_FLIGHT_POLL_MS))
      const existing = await prisma.testQuestion.findUnique({
        where: { cardId_direction: { cardId, direction } }
      })
      if (existing) {
        return NextResponse.json({ cached: true, question: existing })
      }
    }

    // Shared generator: marks (cardId, direction) in flight and upserts, so a
    // concurrent prefetch and this request never both call the model
    testQuestion =
      (await generateAndCacheTestQuestion(card, direction)) ??
      (await prisma.testQuestion.findUniqueOrThrow({
        where: { cardId_direction: { cardId, direction } }
      }))

    prisma.testQuestion.update({
      where: { id: testQuestion.id },
      data: { timesUsed: { increment: 1 } }
    }).catch(err => console.error("Failed to update usage count:", err))

    return NextResponse.json({
      cached: false,
      question: testQuestion
    })

  } catch (error) {
    // Handle aborted requests (from prefetch cancellations) gracefully
    if (error instanceof Error && (error.message === 'aborted' || (error as NodeJS.ErrnoException).code === 'ECONNRESET')) {
      console.log("Request aborted (prefetch cancelled)")
      return NextResponse.json(
        { error: "Request cancelled" },
        { status: 499 } // Client Closed Request
      )
    }

    console.error("Error generating test question:", error)
    if (error instanceof AIResponseError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode })
    }
    if (error instanceof z.ZodError) {
      return NextResponse.json(
        { error: error.issues[0].message },
        { status: 400 }
      )
    }
    return NextResponse.json(
      { error: "Failed to generate question" },
      { status: 500 }
    )
  }
}
